---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: registry-key
data:
  domain.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNtRENDQWdHZ0F3SUJBZ0lKQU9jSUNBT2p3MTlITUEwR0NTcUdTSWIzRFFFQkJRVUFNR1V4Q3pBSkJnTlYKQkFZVEFrRlZNUk13RVFZRFZRUUlEQXBUYjIxbExWTjBZWFJsTVNFd0h3WURWUVFLREJoSmJuUmxjbTVsZENCWAphV1JuYVhSeklGQjBlU0JNZEdReEhqQWNCZ05WQkFNTUZURTVNaTR4TmpndU9Ua3VNVEF3TG01cGNDNXBiekFlCkZ3MHhOekV3TVRjeE5EQXhNVFZhRncweE9ERXdNVGN4TkRBeE1UVmFNR1V4Q3pBSkJnTlZCQVlUQWtGVk1STXcKRVFZRFZRUUlEQXBUYjIxbExWTjBZWFJsTVNFd0h3WURWUVFLREJoSmJuUmxjbTVsZENCWGFXUm5hWFJ6SUZCMAplU0JNZEdReEhqQWNCZ05WQkFNTUZURTVNaTR4TmpndU9Ua3VNVEF3TG01cGNDNXBiekNCbnpBTkJna3Foa2lHCjl3MEJBUUVGQUFPQmpRQXdnWWtDZ1lFQTdIK0R3M3Azb3NaRklZaVdLZFVGNWZRYU5oZWcrTkpTNzQyazBlMFUKdm5tUExxaXFJVHp3b2FDT2pCLy9WcFdNeVEzTlBRczh0dkZCSk55cEZvNE5NNmZSZms5ZjZLS2JwWHRENWNjQQpIMUI4NWMvQXdnbmhqZ2NyRnpKU2w5dzlpN29XZTRiTmY4L1NpbkdyMlJ2aEZqWkt3RFlPSnhnUWJVTTdvK1FzCitIRUNBd0VBQWFOUU1FNHdIUVlEVlIwT0JCWUVGTzVFL1A1VVplZ3JOaGhZUEJlQllTOUUwZitUTUI4R0ExVWQKSXdRWU1CYUFGTzVFL1A1VVplZ3JOaGhZUEJlQllTOUUwZitUTUF3R0ExVWRFd1FGTUFNQkFmOHdEUVlKS29aSQpodmNOQVFFRkJRQURnWUVBSVBadHlCMmljU1B4enJSb1VRbThQYThFNGMxYXVLR0dqZDNXUlI4VG16NkM4R3ZhCndtNUFRUXRHcnptY3Y2RERnaGNMMEZ5VlhIeHpyaURwS1FNNGNpRFZMbmJpVENOUFd1c2RWRTUvYnNkNm9ITmUKZXdaYnpRYnRTY08xODhaeUZ3UlFML3cwTll6SDF2OWd5c3FGMENtY0Q4NWdKY0ZrVThEVUJJMUxXS3c9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  domain.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlDWEFJQkFBS0JnUURzZjRQRGVuZWl4a1VoaUpZcDFRWGw5Qm8yRjZENDBsTHZqYVRSN1JTK2VZOHVxS29oClBQQ2hvSTZNSC85V2xZekpEYzA5Q3p5MjhVRWszS2tXamcwenA5RitUMS9vb3B1bGUwUGx4d0FmVUh6bHo4REMKQ2VHT0J5c1hNbEtYM0QyTHVoWjdoczEvejlLS2NhdlpHK0VXTmtyQU5nNG5HQkJ0UXp1ajVDejRjUUlEQVFBQgpBb0dCQUs5eWplSzMrUWNGeGdWeG1jMGczc1pRaUIxMi9CRjdudEZlcUZhZ1psSkVSZ2VjVXRKanJqU0pzeGFiCktrY21uUklPcmlMS01sbVpzdlZReWhRVWdBOVQ3bWdzM2lDeEpUeWtGRXFXdy9yR3Vudm9XV2Y5bUlrQkg2K0IKV0Y3N0NuL1ZIcEpYcTFacEhaYjJnbVhEQWtaWmpEbkdNb1ByZ2pOT0JaUHdVb3dCQWtFQS96RFhZOVNKWjBZcAovd1dEemNreWM4R0dIM2ZlT05rSzNqN3VZMlJFYm1SU2tYeTkzUGszenI0V0NBSEIwWkFmdkcwVTF6ZmFJZmFGCmIvZ0ZYeGdCc1FKQkFPMC9mNzVzWUhEK2ltcWExeFRuQjY0OG52Z3RZYXBraXl6MmRJMG41WHE5dFBDN2NVVncKc01OS1FhbjhLc2FJYVVJVFcveVJITHd3L0NTMGhxeFpVc0VDUUIyMHhNNEZOcjJENkcyY2FieHgyR0tyTzM2OApTRzBicnUweUxEUDd2dytPdENIbGdJQ1JybEp0eEVqSVU1U2VqMk15MjRNMktEbGQ1aWlqbVpSNVNmRUNRQzFKCmQ3c0R1UTBZcVpkYjR6Nk1NejBoT1Q4cWVvQXFIUjhDRkpGMVVpcXgxNzQwS1pVVnc4Z2pmcEZTSDJBeVhkVk4KR0x3SGZ6SzFMd3hhb1hKNHdvRUNRRWpZRjZGWDI1VjVncVJIWEJvWTRBM1ZkSmhpVW1xNXNydFVua3BMV1dVSAphYWswdll0cTY4Mlh6YVl3bkNKRzkySTNuRzVTOXdxRktJSG9waUFoWFdRPQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: registry
#  namespace: default
#spec:
#  ports:
#  - port: 443
#  selector:
#    kubeless: registry
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: registry
  namespace: default
spec:
  template:
    metadata:
      labels:
        kubeless: registry
    spec:
      containers:
      - env:
        - name: REGISTRY_HTTP_ADDR
          value: "0.0.0.0:443"
        - name: REGISTRY_HTTP_TLS_CERTIFICATE
          value: "/registry-cert/domain.crt"
        - name: REGISTRY_HTTP_TLS_KEY
          value: "/registry-cert/domain.key"
        image: registry:2
        imagePullPolicy: IfNotPresent
        name: registry
        ports:
        - containerPort: 443
        volumeMounts:
        - mountPath: /registry-cert
          name: registry-cert
          readOnly: true
      volumes:
        - name: registry-cert
          secret:
            secretName: registry-key
