# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9 
    working_directory: /go/src/github.com/kubeless/kubeless
    steps:
      # - setup_remote_docker
      - checkout
      # It is not possible to resolve env vars in the environment section:
      # https://discuss.circleci.com/t/using-environment-variables-in-config-yml-not-working/14237
      - run: echo "export CONTROLLER_TAG=${CIRCLE_TAG:-build-$CIRCLE_WORKFLOW_ID}" >> $BASH_ENV
      - run: echo "export CONTROLLER_IMAGE=${CONTROLLER_IMAGE_NAME}:${CONTROLLER_TAG}" >> $BASH_ENV
      # - run: echo "export BUILDER_IMAGE=${BUILDER_IMAGE_NAME}:${CONTROLLER_TAG}" >> $BASH_ENV
      # - run: echo "export KAFKA_CONTROLLER_IMAGE=${KAFKA_CONTROLLER_IMAGE_NAME}:${CONTROLLER_TAG}" >> $BASH_ENV
      # - run: echo "export NATS_CONTROLLER_IMAGE=${NATS_CONTROLLER_IMAGE_NAME}:${CONTROLLER_TAG}" >> $BASH_ENV
      - run: sudo -E make bootstrap
      - run: make VERSION=${CONTROLLER_TAG} binary
      # - run: make test
      # - run: make validation
      # - run: make controller-image CONTROLLER_IMAGE=$CONTROLLER_IMAGE
      - run: make all-yaml
      - persist_to_workspace:
          root: /go
          paths: 
            - bin
            - src/github.com/kubeless/kubeless/*yaml
    environment:
      # TODO: Move this to a context
      CONTROLLER_IMAGE_NAME: bitnami/kubeless-controller-manager
      BUILDER_IMAGE_NAME: kubeless/function-image-builder
      KAFKA_CONTROLLER_IMAGE_NAME: bitnami/kafka-trigger-controller
      NATS_CONTROLLER_IMAGE_NAME: bitnami/nats-trigger-controller
      CGO_ENABLED: "0"
      TEST_DEBUG: "1"
      GKE_VERSION: 1.8.8-gke.0
      MINIKUBE_VERSION: v0.25.2
  minikube:
    machine: true
    environment:
      # TODO: Move this to a context
      CONTROLLER_IMAGE_NAME: bitnami/kubeless-controller-manager
      BUILDER_IMAGE_NAME: kubeless/function-image-builder
      KAFKA_CONTROLLER_IMAGE_NAME: bitnami/kafka-trigger-controller
      NATS_CONTROLLER_IMAGE_NAME: bitnami/nats-trigger-controller
      CGO_ENABLED: "0"
      TEST_DEBUG: "1"
      GKE_VERSION: 1.8.8-gke.0
      MINIKUBE_VERSION: v0.25.2
    steps:
      - checkout
      - run: sudo -E make bootstrap
      - attach_workspace:
          at: /tmp/go
      - run: sudo cp -r /tmp/go/bin/* /usr/local/bin/
      - run: cp -r /tmp/go/src/github.com/kubeless/kubeless/*yaml .
      - run: echo "export CONTROLLER_TAG=${CIRCLE_TAG:-build-$CIRCLE_WORKFLOW_ID}" >> $BASH_ENV
      - run: echo "export CONTROLLER_IMAGE=${CONTROLLER_IMAGE_NAME}:${CONTROLLER_TAG}" >> $BASH_ENV
      - run: echo "export BUILDER_IMAGE=${BUILDER_IMAGE_NAME}:${CONTROLLER_TAG}" >> $BASH_ENV
      - run: echo "export KAFKA_CONTROLLER_IMAGE=${KAFKA_CONTROLLER_IMAGE_NAME}:${CONTROLLER_TAG}" >> $BASH_ENV
      - run: echo "export NATS_CONTROLLER_IMAGE=${NATS_CONTROLLER_IMAGE_NAME}:${CONTROLLER_TAG}" >> $BASH_ENV
      - run: echo "export KUBECFG_JPATH=/go/src/github.com/kubeless/kubeless/ksonnet-lib" >> $BASH_ENV
      - run: echo "export PATH=/go/src/github.com/kubeless/kubeless/bats/libexec:/go/src/github.com/kubeless/kubeless/bats/bin:$PATH" >> $BASH_ENV
      - run: ./script/integration-tests minikube deployment
      - run: ./script/integration-tests minikube basic

workflows:
  version: 2
  kubeless:
    jobs:
      - build
      - minikube:
          requires:
            - build

