# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9 
    working_directory: /go/src/github.com/kubeless/kubeless
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: make bootstrap
      - run: make VERSION=${TRAVIS_TAG:-build-$TRAVIS_BUILD_ID} binary
      - run: make controller-image CONTROLLER_IMAGE=$CONTROLLER_IMAGE
      - run: make all-yaml
      - run: make test
      - run: make validation
