# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9 
    working_directory: /go/src/github.com/kubeless/kubeless
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: |
          echo "
          export CONTROLLER_TAG=${CIRCLE_TAG:-build-$CIRCLE_PREVIOUS_BUILD_NUM}
          export CONTROLLER_IMAGE=${CONTROLLER_IMAGE_NAME}:${CONTROLLER_TAG}
          export BUILDER_IMAGE=${BUILDER_IMAGE_NAME}:${CONTROLLER_TAG}
          export KAFKA_CONTROLLER_IMAGE=${KAFKA_CONTROLLER_IMAGE_NAME}:${CONTROLLER_TAG}
          export NATS_CONTROLLER_IMAGE=${NATS_CONTROLLER_IMAGE_NAME}:${CONTROLLER_TAG}
          \n" >> BASH_ENV
      - run: env
      - run: echo $CONTROLLER_IMAGE
      - run: make bootstrap
      - run: make VERSION=${CONTROLLER_TAG} binary
      - run: kubeless version
      - run: make controller-image CONTROLLER_IMAGE=$CONTROLLER_IMAGE
      - run: make all-yaml
      - run: make test
      - run: make validation
    environment:
      CONTROLLER_IMAGE_NAME: bitnami/kubeless-controller-manager
      BUILDER_IMAGE_NAME: kubeless/function-image-builder
      KAFKA_CONTROLLER_IMAGE_NAME: bitnami/kafka-trigger-controller
      NATS_CONTROLLER_IMAGE_NAME: bitnami/nats-trigger-controller
      CGO_ENABLED: "0"
      TEST_DEBUG: "1"
      GKE_VERSION: 1.8.8-gke.0
      MINIKUBE_VERSION: v0.25.2
